Bookstore/src/books/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import home, BookListView, BookDetailView


app_name = 'books' 

urlpatterns = [
    path('', home, name='home'),
    path('list/', BookListView.as_view(), name='list'),
    path('list/<pk>', BookDetailView.as_view(), name='detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bookstore/src/bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls', namespace='sales')),
    path('books/', include('books.urls', namespace='books')),
    # path('customers/', include('customers.urls')),
    # path('salespersons/', include('salespersons.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bookstore/src/sales/urls.py
from django.urls import path
from .views import home, records

app_name = 'sales' 

urlpatterns = [
    path('', home, name='home'),
    path('sales/', records, name='records'),
]

Bookstore/src/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Bookstore{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'base/css/style.css' %}">
    {% block extra_css %}{% endblock %}
    {% block extra_js %}{% endblock %}
</head>
<body>
    <header>
        <nav>
            <a href="{% url 'sales:home' %}" class="nav-link">Home</a>
            <a href="{% url 'books:home' %}" class="nav-link">Books</a>
            <a href="{% url 'books:list' %}" class="nav-link">Books List</a>
            <a href="{% url 'sales:records' %}" class="nav-link">Sales Records</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="nav-link">Logout</a>
            {% else %}
                <a href="{% url 'login' %}" class="btn">Login</a>
            {% endif %}
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <p>&copy; 2023 Bookstore. All rights reserved.</p>
    </footer>
</body>
</html>